const DARK_MODE_SUCCESS = 'DARK_MODE_SUCCESS';
const DARK_MODE_FAILURE = 'DARK_MODE_FAILURE';
const RESUME_ACTIVE_SUCCESS = 'RESUME_ACTIVE_SUCCESS';
const RESUME_ACTIVE_FAILURE = 'RESUME_ACTIVE_FAILURE';

export { DARK_MODE_SUCCESS, DARK_MODE_FAILURE, RESUME_ACTIVE_SUCCESS, RESUME_ACTIVE_FAILURE };
