const DARK_MODE_SUCCESS = 'DARK_MODE_SUCCESS';
const DARK_MODE_FAILURE = 'DARK_MODE_FAILURE';
const HIDE_DARK_MODE_SUCCESS = 'HIDE_DARK_MODE_SUCCESS';
const HIDE_DARK_MODE_FAILURE = 'HIDE_DARK_MODE_FAILURE';

export { DARK_MODE_SUCCESS, DARK_MODE_FAILURE, HIDE_DARK_MODE_SUCCESS, HIDE_DARK_MODE_FAILURE };
